config/routes.rb
MyNewApp::Application.routes.draw do
  root 'static#home'
  get '/about' => 'static#about'
  get '/cat-pictures' => 'static#cats'
  get '/cat-pictures(/:number_of_cats)' => 'static#cats', as: :cat_pictures

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

  def cats
    @cats = CatAPI.new.get_images(results_per_page: params[:number_of_cats] || 1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
  def current_date_and_time
    Time.now.strftime('%B %-d, %Y at %-1:%M%P')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Erika's Cat App</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <center>
      <p><%= link_to 'Home', root_path %> | <%= link_to 'About', about_path %> | <%= link_to 'Cat Pictures', cat_pictures_path %><p>
    </center>

    <%= yield %>

    <hr>

    <center>
      <p>It is currently <%= Time.now.strftime("%B %-d, %Y at %-l:%M%P") %>.</p>
    </center>

  </body>
</html>